name: Test docker image

on:
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build image
              run: docker build -t bugsnag-event-csv .

            - name: Check image output
              run: docker run -it bsc --help | grep "Options:"