name: Run tests

on:
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - '7.4'
                    - '8.0'
                    - '8.1'
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}

            - name: Install dependencies
              run: composer install

            - name: Run tests
              run: composer test

            - name: Build image
              run: docker build -t bugsnag-event-csv .

            - name: Check image output
              run: docker run bugsnag-event-csv --help | grep "Options:"