name: Tests

on:
    - push

jobs:
    test:
        runs-on: ubuntu-latest
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            fail-fast: false
            matrix:
                php_version:
                    - '7.4'
                    - '8.0'
                experimental:
                    - false
                include:
                    - php_version: '8.1'
                      experimental: true
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
            - name: Install dependencies
              run: composer install
            - name: Run tests
              run: composer test
